% !TeX encoding = UTF-8
% !TeX spellcheck = en_GB
\documentclass[a4paper, 11pt, extrafontsizes, onecolumn, openright]{memoir}

%%% PACKAGES 
%%%------------------------------------------------------------------------------
\usepackage{EcoFoG}
\usepackage{blkarray} % Matrices annotées

%%% COMMANDS 
%%%------------------------------------------------------------------------------
% Réduction de l'espacement vertical entre le code R et les résultats
\renewenvironment{knitrout}{\setlength{\topsep}{1mm}}{} 
% Espace agrandi pour les numéros de parties dans la table des matières {défaut: 1.5em}
\setlength{\cftpartnumwidth}{2em}
% Notation diversité (ex.: \xq[\,]{D}{q}{\matrixsym{Z}}{\alpha})
\newcommand*{\xq}[6][]{
  {#1^{#3}_{#6}\!#2^{#4}_{#5}}
}
\newenvironment{Essentiel}
  {\begin{bclogo}[logo=\bctrombone, noborder=true, couleur=lightgray!50]{Key Points}\parindent0pt}
  {\end{bclogo}}


%%% BIBLIOGRAPHY FILE
%%%------------------------------------------------------------------------------
\addbibresource{library.bib}
 
%%% THE DOCUMENT
%%%-------------------------------------------------------------------------------

\author{Eric Marcon}
\title{The Measurement of Biodiversity}
\date{February, 3 2018}


%%%------------------------------------------------------------------------------
\begin{document}
<<Declarations, echo=FALSE, include=FALSE>>=
# Install necessary packages
InstallPackages <- function(Packages) {
  sapply(Packages, function(Package) if (!Package %in% installed.packages()[, 1]) {install.packages(Package, repos="https://cran.rstudio.com/")})
}
InstallPackages(c("ade4", "adespatial", "entropart", "entropy", "EntropyEstimation", "gplots", "ggplot2", "iNEXT", "knitr", "sp", "SPECIES", "untb", "vegan"))
# knitr and document format options (copied into child documents)
library("knitr")
opts_knit$set(concordance=TRUE)
# Set global chunk options
opts_chunk$set(cache=TRUE, warning=FALSE, tidy=TRUE, fig.width=8, fig.height=6, out.width='.8\\maxwidth', tidy.opts=list(blank=FALSE, width.cutoff=60), size="scriptsize")
options(width=60)
# Postscript plots
setEPS(horizontal=FALSE, onefile=FALSE, paper="special", family="ComputerModern", encoding="TeXtext.enc", width=8.0, height=6.0)
par(mar=c(0,0,0,0))
# ggplot style
library("ggplot2")
ggstyle <- list(scale_colour_grey(), theme_bw(), theme(legend.position="none"))
@


\selectlanguage{english}
\sisetup{locale = UK}

%%%------------------------------------------------------------------------------
\frontmatter

% Main title Page
\MainTitlePage[
I thank François Morneau for his careful proof reading of the first version of this docuemnt and his decisive contribution to the optimal use of R code in examples.

Bruno Hérault and Chris Baraloto contributed significantly to the review of the literature.

The original English translation was made by Tim Chubb.

This document is reproducibly and dynamically made with:
\begin{itemize}
  \item \LaTeX, in its Miktex (\url{http://miktex.org/}) distibution anf the \emph{memoir} class(\url{http://www.ctan.org/pkg/memoir});
  \item R (\url{http://www.r-project.org/}) and RStudio (\url{http://www.rstudio.com/});
  \item \emph{knitr} (\url{http://yihui.name/knitr/}).
\end{itemize}

Its source code is published on GitHub (\url{https://github.com/EricMarcon/BDMeasurement}).
]

\SmallMargins

\setcounter{tocdepth}{3} % subsubsection
\tableofcontents

\clearpage

% <<child-Notations, child='Notations.Rnw'>>=
% @

%%%------------------------------------------------------------------------------
\mainmatter

\SmallMargins
\part{Notions and tools}
\label{part:Notions}
<<child-Notions, child='Notions.Rnw'>>=
@
\clearpage



% \SmallMargins
% \part{Neutral Diversity of a Community}
% \label{part:Neutre}
% <<child-Neutre, child='Neutre.Rnw'>>=
% @
% \clearpage
% 
% 
% 
% \SmallMargins
% \part{Functional and Phylogenetic Diversity}
% \label{part:Phylodiversite}
% <<child-Phylodiversite, child='Phylodiversite.Rnw'>>=
% @
% \clearpage
% 
% 
% 
% \SmallMargins
% \part[Beta Diversity and Partitioning]{$\beta$ Diversity and Partitioning}
% \label{part:Beta}
% <<child-Beta, child='Beta.Rnw'>>=
% @
% \clearpage
% 
% 
% 
% \SmallMargins
% \part{Joint Diversity, Structural Diversity}
% \label{part:Jointe}
% <<child-Jointe, child='Jointe.Rnw'>>=
% @
% \clearpage
% 
% 
% 
% \SmallMargins
% \part{Spatially Explicit Diversity}
% \label{part:Spatial}
% <<child-Spatial, child='Spatial.Rnw'>>=
% @
% \clearpage
% 
% 
% 
% \SmallMargins
% \part{Conclusion}
% \label{part:Conclusion}
% <<child-Conclusion, child='Conclusion.Rnw'>>=
% @
% \clearpage



%%%------------------------------------------------------------------------------
\backmatter
\clearpage

%%% BIBLIOGRAPHY
%%% -------------------------------------------------------------

\SmallMargins

\twocolumn
\renewcommand*{\bibfont}{\scriptsize}
\printbibliography

\onecolumn


\end{document}
